### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by kmsalah** [CarolinaIgnites/editFrame#13]
Sometimes scroll bars appear on the iframe and it messes up gameplay. They disappear if you click on the meta tab and run the game, so it may have something to do with the tabs

**Comment by dmadisetti** [comment]
This happens because the code area overflows causes a scroll bar to appear on the entire page causing the iframe to become smaller. Changing tabs moves you to a page with no overflow, causing the iframe to return to the correct size.

It can be fixed by ensuring overflow occurs on the code text area and not the whole page or triggering responsive resizing on the overflow cases.
